# Configuration statique

[global]
  sendAnonymousUsage = false

[log]
  level = "INFO" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format = "common"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false

[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[providers]
  [providers.file]
    filename = "/etc/traefik/dynamic-conf.toml"
    watch = true

[certificatesResolvers.herveGuigoz.acme]
  email = "herve.guigoz@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.herveGuigoz.acme.httpChallenge]
    entryPoint = "http"